spring:
  application:
    name: goal-like

spring.config:
  import: secrets.yml

spring.profiles:
  active: dev

notification:
  email:mock: "true"

spring.data:
    rest:
      base-path: /api/v1
      default-media-type: application/json